### ISSUE TITLE
collection_class=set is not supported

### ISSUE THREAD

**Issue by ptallada** [ITCase/pyramid_sacrud#100]
Hi!

I have a model with some relationships configured with collection_class=set.
But when I try to insert a new record it tries to call the constructor with the collection as a list, and that fails with following error.

A workaround is to override the class constructor. But maybe it is better if pyramid_sacrud could cast the iterable to the collection_class type.

Traceback (most recent call last):
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/pyramid_sacrud/views/CRUD.py", line 140, in sa_add
    obj = self.crud.create(data)
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sacrud/action.py", line 66, in create
    return self._add(obj, data, **kwargs)
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sacrud/action.py", line 183, in _add
    .add(self.session, data, self.table)
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sacrud/preprocessing.py", line 206, in add
    return self.obj(**params)
  File "<string>", line 4, in __init__
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 269, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 526, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 226, in __set__
    instance_dict(instance), value, None)
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1009, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1025, in _set_iterable
    new_values = list(adapter(new_collection, iterable))
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1009, in <lambda>
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/home/tallada/Projectes/env/cosmohub_v5/local/lib/python2.7/site-packages/sqlalchemy/orm/collections.py", line 646, in adapt_like_to_iterable
    given, wanted))
TypeError: Incompatible collection type: list is not set-like

**Comment by ptallada** [comment]
Quick fix in preprocessing.py, checking if the collection_class attribute is defined and using it to wrap the list.

Lines 55-58:

    if relation.property.collection_class:
        return relation.property.collection_class(objs.all())
    else:
        return objs.all()

**Comment by uralbash** [comment]
@ptallada Thanks!
This is a very special case, it works quite as shown below:

```python
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Item(Base):
    __tablename__ = 'item'
    id = Column(Integer, primary_key=True)
    notes = relationship("Note",
                collection_class=set,
                cascade="all, delete-orphan")


class Note(Base):
    __tablename__ = 'note'
    id = Column(Integer, primary_key=True)
    item_id = Column(Integer, ForeignKey('item.id'), nullable=False)
    keyword = Column(String)
    text = Column(String)

    def __init__(self, keyword, text):
        self.keyword = keyword
        self.text = text

item = Item()
note = Note("foo", "bar")
Item.notes.property.collection_class([note, ])  # OK
```
But I can use other Classes, for example (http://docs.sqlalchemy.org/en/rel_0_9/orm/collections.html#dictionary-collections):

```python

from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.orm.collections import attribute_mapped_collection
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Item(Base):
    __tablename__ = 'item'
    id = Column(Integer, primary_key=True)
    notes = relationship("Note",
                collection_class=attribute_mapped_collection('keyword'),
                cascade="all, delete-orphan")


class Note(Base):
    __tablename__ = 'note'
    id = Column(Integer, primary_key=True)
    item_id = Column(Integer, ForeignKey('item.id'), nullable=False)
    keyword = Column(String)
    text = Column(String)

    def __init__(self, keyword, text):
        self.keyword = keyword
        self.text = text

item = Item()
note = Note("foo", "bar")
Item.notes.property.collection_class([note, ])
```

And it raises error:

```python
Traceback (most recent call last):
  File "foofoo.py", line 30, in <module>
    Item.notes.property.collection_class([note, ])
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```
This is most likely a bug in sacrud, but I don't know how it to best solve at the moment
